/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GameDocType {
  id: string;
  name: string;
  type: "highestScore" | "lowestScore";
  scores: string[];
  previous: string;
  createdAt?: string;
  updatedAt?: string;
  [k: string]: unknown;
}
